# meta-lochan/conf/auto.conf

PREFERRED_PROVIDER_virtual/kernel = "linux-custom-lochan"
PREFERRED_VERSION_linux-custom-lochan = "6.15%"

DISTRO_FEATURES:append = " virtualization xen"
IMAGE_INSTALL:append = " \
    kernel-module-xen-blkback \
    kernel-module-xen-gntalloc \
    kernel-module-xen-gntdev \
    kernel-module-xen-netback \
    kernel-module-xen-wdt \
    xen \
    xen-tools \
    xen-tools-xenstat \
    "

